---
classoption: landscape
---

```{r echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
library(dataRetrieval)
library(dplyr)
library(lubridate)
library(gsplot)
library(knitr)

source("../R/functions-depthprofiles.R")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
wy_dates <- convertWYtoDate(wy)
wy_start <- wy_dates$wy_start
wy_end <- wy_dates$wy_end

# pull in ranges from csv file & filter for just this site
column_classes <- c(rep("character", 2), rep("numeric", 8))
plotRanges <- read.csv("../data/depthProfileRanges.csv", colClass=column_classes) %>% 
  filter(site_no == siteNumber)

pcodes <- c("00098", "00300", "00010", "00400", "00095")

qw_nwis <- readNWISqw(siteNumbers = siteNumber, 
                      parameterCd = pcodes, 
                      startDate = wy_start, 
                      endDate = wy_end)

if(nrow(qw_nwis)!=0){
  prof_data <- filterLakeDepthProfileData(qw_nwis)
} else {
  prof_data <- paste0("No water quality data available \n",
                      "http://waterdata.usgs.gov/nwis/inventory?agency_code=USGS&site_no=",
                      siteNumber)
}
```

`r isData <- class(prof_data) == "list"`

#`r if(!isData) {prof_data}`#

```{r eval=isData, echo=FALSE, warning=FALSE, message=FALSE} 
#grab data from big list
dates_uniq <- prof_data$dates_uniq
DO <- prof_data$DO
h2otemp <- prof_data$h2otemp
PH <- prof_data$PH
specifcond <- prof_data$specifcond

#setup plot titles
DO_title <- "DISSOLVED OXYGEN (D.O.) IN MILLIGRAMS PER LITER"
h2otemp_title <- "WATER TEMPERATURE (W.T.) IN DEGREES CELCIUS"
PH_title <- "PH IN STANDARD UNITS"
specifcond_title <- "SPECIFIC CONDUCTANCE (S.C.) IN MICROSIEMENS PER CENTIMETER AT 25 DEGREES CELCIUS"

#figuring out how many 2x4 sets there are, and then how many extra
num_plots <- length(dates_uniq)
num_2x5_plots <- floor(num_plots/5)
num_extra_plots <- num_plots%%5
isEven <- num_extra_plots%%2 == 0

```

```{r eval=isData, echo=FALSE, warning=FALSE, message=FALSE, results = 'asis', fig.width=8, fig.height=6.5}

#set plot options for margins (in order to fit text)
par(oma = c(5,4,4,0) + 0.1,
    mar = c(1,1,5,1) + 0.1)

#2x5 plots
if(num_2x5_plots != 0){
  plot_setup <- matrix(1:10, 2, 5)
  d <- 1
  for(p in seq(num_2x5_plots)){
    if(p > 1){cat("\n\\newpage\n")}
    dts <- dates_uniq[d:(p*5)]
  
    layout(plot_setup)
    for(t in seq_along(dts)){
      left_logic <- t == 1 #is it the farthest left plot
      print(depthProfilePlot(side1 = h2otemp, side3 = DO, 
                             filter_date = dts[t], top = TRUE, 
                             left = left_logic, xranges = plotRanges))
      print(depthProfilePlot(side1 = specifcond, side3 = PH, 
                             filter_date = dts[t], top = FALSE, 
                             left = left_logic, xranges = plotRanges))
    }
    
    #add titles around the plot
    title(ylab = "DEPTH, IN METERS",
          outer = TRUE, line = 2)
    title(xlab = specifcond_title,
          outer = TRUE, line = 1)
    title(xlab = PH_title,
          outer = TRUE, line = -17.5)
    title(xlab = h2otemp_title,
          outer = TRUE, line = -19.5)
    title(xlab = DO_title,
          outer = TRUE, line = -37.5)
  
    d <- (p*4)+1
  }
} 

```

`r if(isEven){opts_chunk$set(fig.width = 6.5)}`
`r if(!isEven){opts_chunk$set(fig.width = 8)}`

```{r eval=isData, echo=FALSE, warning=FALSE, message=FALSE, results = 'asis', fig.height=6.5}

#set plot options for margins (in order to fit text)
par(oma = c(5,4,4,0) + 0.1,
    mar = c(1,1,5,1) + 0.1)

#extra plots that don't make a full 2x5 set 
dts <- tail(dates_uniq, num_extra_plots)
if(length(dts) > 0){
  cat("\n\\newpage\n")
  
  num_plots_on_page <- ifelse(isEven, 4, 5)
  num_before_after <- (num_plots_on_page - num_extra_plots)/2 #number of blank plots to center
  if(num_extra_plots == 1){
    ylabel_line <- -15
  } else if(num_extra_plots == 2){
    ylabel_line <- -10
  } else {
    ylabel_line <- 2
  }
  
  plot_setup <- matrix(1:(2*num_plots_on_page), 2, num_plots_on_page)
  layout(plot_setup)

  for(b in 1:num_before_after){
    plot.new()
    plot.new()
  }
  
  for(t in seq_along(dts)){
    left_logic <- t == 1 #is it the farthest left plot
    print(depthProfilePlot(side1 = h2otemp, side3 = DO, 
                           filter_date = dts[t], top = TRUE, 
                           left=left_logic, xranges=plotRanges))
    print(depthProfilePlot(side1 = specifcond, side3 = PH, 
                           filter_date = dts[t], top = FALSE, 
                           left = left_logic, xranges = plotRanges))
  }
  
  for(b in 1:num_before_after){
    plot.new()
    plot.new()
  }
  
  #add titles around the plot
  title(ylab = "DEPTH, IN METERS",
        outer = TRUE, line = ylabel_line)
  title(xlab = specifcond_title,
        outer = TRUE, line = 1)
  title(xlab = PH_title,
        outer = TRUE, line = -17.5)
  title(xlab = h2otemp_title,
        outer = TRUE, line = -19.5)
  title(xlab = DO_title,
        outer = TRUE, line = -37.5)

}

```
