---
classoption: landscape
output: 
  word_document:
    reference_docx: table_style.docx
---

```{r echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
library(dataRetrieval)
library(lubridate)
library(dplyr)
library(tidyr)

source("../R/functions-ghtable.R")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
wy_dates <- convertWYtoDate(wy)
wy_start <- wy_dates$wy_start
wy_end <- wy_dates$wy_end

stage_data <- readNWISdata(service = "dv", sites = siteNumber, 
                           parameterCd = "00065", startDate = "1800-01-01", 
                           endDate = wy_end)
if(nrow(stage_data)!=0){
  ghtable <- makeGageHeightTable(stage_data, wy_start)
} else {
  ghtable <- paste0("No gage height data available \n",
                  "http://waterdata.usgs.gov/nwis/inventory?agency_code=USGS&site_no=",
                  siteNumber)
}
``` 

`r isData <- !is.null(dim(ghtable))`

#`r if(!isData) {ghtable}`#

`r isWord <- output == "word"`
```{r eval=!isWord && isData, echo=FALSE, warning=FALSE, message=FALSE, results='asis'} 
library(xtable)
options(xtable.comment = FALSE)

gh_xtable <- xtable(ghtable, auto=TRUE)
print.xtable(gh_xtable, include.rownames=FALSE)
```

```{r eval=isWord && isData, echo=FALSE, warning=FALSE, message=FALSE, results='asis'} 
library(pander)
panderOptions('table.continues', NULL)
panderOptions('table.split.table', Inf)
pander(ghtable)
```
