---
output: 
  word_document:
    reference_docx: qwtimeseries_style.docx
---

```{r echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
library(dataRetrieval)
library(dplyr)
library(lubridate)
library(gsplot)

source("../R/functions-qwtimeseries.R")
```

```{r echo=FALSE, warning=FALSE, message=FALSE} 
wy_dates <- convertWYtoDate(wy)
wy_end <- wy_dates$wy_end

pcodes <- c("00665", "70953", "32210", "00078", "00098")

qw_historic <- readNWISqw(siteNumbers = siteNumber, 
                          parameterCd = pcodes,
                          startDate = "1800-01-01", 
                          endDate = wy_end)

isData <- nrow(qw_historic)!=0

```

#`r if(!isData) {paste("No water quality data available for", siteNumber)}`#

```{r eval=isData, echo=FALSE, warning=FALSE, message=FALSE, fig.height = 14, fig.width=11}
depth <- filterParmData(qw_historic, "00098")
totalP <- filterParmData(qw_historic, "00665", isTotalP = TRUE, depth) 
chlorophyll <- filterParmData(qw_historic, c("32210", "70953"), depth)
secchi <- filterParmData(qw_historic, "00078", depth)
trophic <- calcTrophicIndex(totalP, chlorophyll, secchi)

# getting correct dates for labels/axis ticks
all_dates <- year(c(totalP$sample_dt, chlorophyll$sample_dt, secchi$sample_dt, trophic$sample_dt))
firstDate <- as.Date(paste0(min(all_dates), "-01-01"))
lastDate <- as.Date(format(wy_dates$wy_end, "%Y-12-31"))
yrs <- seq(firstDate, lastDate, by = "years")
date_info <- list(firstDate = firstDate, lastDate = lastDate, yrs = yrs)

lake_nm <- attr(qw_historic, "siteInfo")$station_nm
plot_main_title <- paste(siteNumber, lake_nm)
plot_sub_title <- "Surface total phosphorus, chlorophyll a concentrations, Secchi depths, and TSI data"
totalP_title <- "TOTAL PHOSPHORUS CONCENTRATION\nIN MILLIGRAMS PER LITER"
chlorophyll_title <- "CHLOROPHYLL CONCENTRATION\nIN MICROGRAMS PER LITER"
secchi_title <- "SECCHI DEPTH, IN METERS"
trophic_title <- "TROPHIC STATE INDEX"


# start setting up plot


plot_layout <- matrix(c(1,2,2,3,3,4,4,5,5,6), 10, 1)
plot_title <- makeTitlePlot(main = plot_main_title, subtitle = plot_sub_title)
plot_p <- makeTimeseriesPlot(totalP, totalP_title, date_info, ylim_buffer = 0.05, top_margin = 0)
plot_chloro <- makeTimeseriesPlot(chlorophyll, chlorophyll_title, date_info, ylim_buffer = 0.05)
plot_secchi <- makeTimeseriesPlot(secchi, secchi_title, date_info,
                   axisFlip = TRUE, ylim_buffer = 0.05)
plot_tsi <- makeTimeseriesPlot(trophic, trophic_title, date_info, isTrophicIndex = TRUE,
                               addLegend = plot_secchi$legend, bottom_margin = 0)
plot_legend <- makeLegendPlot(plot_tsi$legend)

layout(plot_layout)
par(oma = c(0,0,0,0))
plot_title
plot_p
plot_chloro
plot_secchi
plot_tsi
plot_legend

```

