---
classoption: landscape
---

```{r echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
library(dataRetrieval)
library(lubridate)
library(dplyr)
library(gsplot)

source("../R/functions-stagehydrograph.R")
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
wy_dates <- convertWYtoDate(wy)
wy_start <- wy_dates$wy_start
wy_end <- wy_dates$wy_end

extraInfo <- list(...)
isDevilsLake <- siteNumber %in% c('05404500')
if(!is.null(extraInfo$filePath)){
  stage_data <- read.csv(extraInfo$filePath)
  stagehydrograph <- makeStageHydrograph_file(stage_data, 
                                              extraInfo$dateTime, 
                                              extraInfo$gageHeight)
} else {
  startDate <- ifelse(test = isDevilsLake, 
                      yes = "1936-01-01", 
                      no = "1800-01-01")
  stage_data <- readNWISdata(service = "dv", sites = siteNumber, 
                           parameterCd = "00065", startDate = startDate, 
                           endDate = wy_end)

  if(nrow(stage_data)!=0){
    stagehydrograph <- makeStageHydrograph_dataRetrieval(stage_data)
  } else {
    stagehydrograph <- paste0("No stage data available \n",
                              "http://waterdata.usgs.gov/nwis/inventory?agency_code=USGS&site_no=",
                              siteNumber)
  }
}

```

`r isPlot <- class(stagehydrograph) == "gsplot"`

#`r if(!isPlot) {stagehydrograph}`#

```{r eval=isPlot, echo=FALSE, warning=FALSE, message=FALSE, fig.width = 14}
stagehydrograph
```
